# Generated by Django 4.2.7 on 2025-03-26 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hoursofservice",
            options={"verbose_name_plural": "Hours of Service"},
        ),
        migrations.RenameField(
            model_name="tripstop",
            old_name="stop_type",
            new_name="type",
        ),
        migrations.AlterField(
            model_name="hoursofservice",
            name="cycle_used",
            field=models.FloatField(
                default=0.0,
                help_text="Hours used in 70-hr/8 days cycle",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(70),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="hoursofservice",
            name="daily_used",
            field=models.FloatField(
                default=0.0,
                help_text="Hours used in 14-hr daily window",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(14),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="hoursofservice",
            name="driving_used",
            field=models.FloatField(
                default=0.0,
                help_text="Hours used in 11-hr driving limit",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(11),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "scheduled"),
                    ("ACTIVE", "active"),
                    ("COMPLETED", "completed"),
                    ("CANCELLED", "cancelled"),
                ],
                default="SCHEDULED",
                max_length=20,
            ),
        ),
    ]
