# Generated by Django 4.2.7 on 2025-03-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_hoursofservice_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripstop",
            name="coordinates",
            field=models.CharField(default=1, max_length=100),
        ),
    ]
