# Generated by Django 4.2.7 on 2025-03-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_logactivity_end_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logactivity",
            name="duration",
        ),
        migrations.AddField(
            model_name="logactivity",
            name="end_time",
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name="logactivity",
            name="start_time",
            field=models.CharField(default=1, max_length=10),
        ),
    ]
